# Generated by Django 4.1.3 on 2022-11-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='year',
            field=models.DateField(max_length=10),
        ),
    ]
